slam_toolbox:
  ros__parameters:

    #Toolbox Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /laser/scan
    mode: mapping #localization
    # debug_logging: false
    throttle_scans: 1  #Number of scans to throttle in synchronous mode
    transform_publish_period: 0.02  #The map to odom transform publish period. 0 will not publish transforms
    map_update_interval: 1.0  #Interval to update the 2D occupancy map for other applications / visualization
    resolution: 0.05  #Resolution of the 2D occupancy map to generate
    max_laser_range: 8.0  #Maximum laser range to use for 2D occupancy map rasterizing
    minimum_time_interval: 0.5  #The minimum duration of time between scans to be processed in synchronous mode
    transform_timeout: 0.2  #TF timeout for looking up transforms
    tf_buffer_duration: 30. #Duration to store TF messages for lookup. Set high if running offline at multiple times speed in synchronous mode.
    stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
    enable_interactive_mode: true

    #Matcher Parameters
    use_scan_matching: true
    use_scan_barycenter: true #Whether to use the barycenter or scan pose
    minimum_travel_distance: 0.25
    minimum_travel_heading: 0.25 #Minimum changing in heading to justify an update
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true